### ISSUE TITLE
Old fire incident data files?

### ISSUE THREAD

**Issue by shftan** [CityofPittsburgh/fire_risk_analysis#2]
Hi, per your readme, I went to to WPRDC (https://data.wprdc.org/dataset/fire-incidents-in-city-of-pittsburgh) to look for the two fire incident data files (on lines 185 and 186 of riskmodel.py), but WPRDC seems to have a new version of that data, in only one csv file. 

Would it be possible to upload your versions of these two fire incident data files to the Github repo?

https://github.com/CityofPittsburgh/fire_risk_analysis/blob/a169dd8409b33c1fc3227c5a770aaece58d105d9/riskmodel.py#L185

**Comment by mmadaio** [comment]
Hi Sarah,

Unfortunately, the specific fire incident files used in the script are kept private, due to privacy concerns (they're logged at individual address levels). 

The public fire incident data on WPRDC, however, is aggregated at the block level to prevent such issues. However, we don't have a version of the script designed to work at the block level. 

I'll add a note to the Readme to make that more clear. 

Thanks!
